title: Ravi Shankar's Blog Series
name: My Experiments With Code
description: In my blog i will be focussing on the generic problems which we face while doing development and at the same time try to cover the latest open source frameworks. I will also be talking about how to properly design and architect the software.
permalink: '/:year/:month/:day/:title/'
baseurl: "/codelab" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ravi Shankar Anupindi # add your name
author-img: RaviShankar.jpg # add your photo
about-author: I am a Software Architect @Infosys Limitied, India. I am passionate about learning and exploring new technolgies. <p> I love coding and have developed many frameworks and utilities which are being used across projects. # add description
social-github: infyravi # add your Github handle
social-linkedin: ravi-shankar-anupindi-160b3b4b # add your Linkedin handle
social-email: iamravi79@gmail.com # add your Email address

# Disqus
discus-identifier: ravi79 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

